import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../data/models.dart';

/// The bundled Helvetica font corrupts the page layout if it hits an en/em
/// dash, curly quote, or ellipsis, so every dynamic string is sanitized first.
String _safe(String input) {
  return input
      .replaceAll('–', '-')
      .replaceAll('—', '-')
      .replaceAll('‘', "'")
      .replaceAll('’', "'")
      .replaceAll('“', '"')
      .replaceAll('”', '"')
      .replaceAll('…', '...');
}

const _ink = PdfColor.fromInt(0xFF2D3142);
const _inkSecondary = PdfColor.fromInt(0xFF6B7086);
const _accent = PdfColor.fromInt(0xFF5A6AAE);
const _hairline = PdfColor.fromInt(0xFFEFE9DD);
const _successTint = PdfColor.fromInt(0xFFEAF0E4);
const _successDeep = PdfColor.fromInt(0xFF4E7139);
const _accentTint = PdfColor.fromInt(0xFFEAEDF6);

/// Builds a one-page PDF export of a student's Experience Passport.
Future<Uint8List> buildPassportPdf({
  required StudentProfile student,
  required List<PassportEntry> entries,
  required Map<String, int> skillCounts,
}) async {
  final doc = pw.Document();
  final sortedSkills = skillCounts.entries.toList()
    ..sort((a, b) => b.value.compareTo(a.value));

  doc.addPage(
    pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.fromLTRB(36, 32, 36, 32),
      header: (context) => pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'ALULINK · EXPERIENCE PASSPORT',
            style: pw.TextStyle(
              fontSize: 9,
              color: _inkSecondary,
              fontWeight: pw.FontWeight.bold,
              letterSpacing: 1,
            ),
          ),
          pw.SizedBox(height: 8),
          pw.Divider(color: _hairline, thickness: 1),
        ],
      ),
      footer: (context) => pw.Align(
        alignment: pw.Alignment.centerRight,
        child: pw.Text(
          'Generated by ALULink · Page ${context.pageNumber} of ${context.pagesCount}',
          style: pw.TextStyle(fontSize: 8, color: _inkSecondary),
        ),
      ),
      build: (context) => [
        pw.Text(
          _safe(student.name),
          style: pw.TextStyle(
            fontSize: 22,
            fontWeight: pw.FontWeight.bold,
            color: _ink,
          ),
        ),
        pw.SizedBox(height: 4),
        pw.Text(
          _safe('${student.program} · ${student.cohort} · ${student.city}'),
          style: const pw.TextStyle(fontSize: 11, color: _inkSecondary),
        ),
        pw.SizedBox(height: 6),
        pw.Text(
          '${entries.length} verified role${entries.length == 1 ? '' : 's'}  ·  '
          '${skillCounts.length} endorsed skill${skillCounts.length == 1 ? '' : 's'}',
          style: pw.TextStyle(
            fontSize: 10,
            fontWeight: pw.FontWeight.bold,
            color: _accent,
          ),
        ),
        pw.SizedBox(height: 22),
        pw.Text(
          'WORK HISTORY',
          style: pw.TextStyle(
            fontSize: 10.5,
            fontWeight: pw.FontWeight.bold,
            color: _inkSecondary,
            letterSpacing: 1,
          ),
        ),
        pw.SizedBox(height: 10),
        for (final entry in entries)
          pw.Container(
            margin: const pw.EdgeInsets.only(bottom: 12),
            padding: const pw.EdgeInsets.all(12),
            decoration: pw.BoxDecoration(
              border: pw.Border.all(color: _hairline),
              borderRadius: pw.BorderRadius.circular(10),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text(
                      _safe(entry.role),
                      style: pw.TextStyle(
                        fontSize: 12.5,
                        fontWeight: pw.FontWeight.bold,
                      ),
                    ),
                    pw.Text(
                      _safe(entry.dates),
                      style: const pw.TextStyle(
                        fontSize: 9.5,
                        color: _inkSecondary,
                      ),
                    ),
                  ],
                ),
                pw.SizedBox(height: 2),
                pw.Text(
                  _safe('${entry.startup.name} · ${entry.verifiedOn}'),
                  style: pw.TextStyle(fontSize: 9.5, color: _accent),
                ),
                pw.SizedBox(height: 8),
                pw.Text(
                  _safe('"${entry.quote}"'),
                  style: pw.TextStyle(
                    fontSize: 10,
                    fontStyle: pw.FontStyle.italic,
                    color: _ink,
                  ),
                ),
                pw.SizedBox(height: 4),
                pw.Text(
                  _safe('- ${entry.author}'),
                  style: const pw.TextStyle(fontSize: 9, color: _inkSecondary),
                ),
                pw.SizedBox(height: 8),
                pw.Wrap(
                  spacing: 6,
                  runSpacing: 6,
                  children: [
                    for (final s in entry.skills)
                      pw.Container(
                        padding: const pw.EdgeInsets.symmetric(
                          horizontal: 8,
                          vertical: 4,
                        ),
                        decoration: pw.BoxDecoration(
                          color: _successTint,
                          borderRadius: pw.BorderRadius.circular(999),
                        ),
                        child: pw.Text(
                          _safe(s),
                          style: pw.TextStyle(
                            fontSize: 8.5,
                            fontWeight: pw.FontWeight.bold,
                            color: _successDeep,
                          ),
                        ),
                      ),
                  ],
                ),
              ],
            ),
          ),
        pw.SizedBox(height: 10),
        pw.Text(
          'SKILL ENDORSEMENTS',
          style: pw.TextStyle(
            fontSize: 10.5,
            fontWeight: pw.FontWeight.bold,
            color: _inkSecondary,
            letterSpacing: 1,
          ),
        ),
        pw.SizedBox(height: 10),
        pw.Wrap(
          spacing: 6,
          runSpacing: 6,
          children: [
            for (final s in sortedSkills)
              pw.Container(
                padding: const pw.EdgeInsets.symmetric(
                  horizontal: 10,
                  vertical: 5,
                ),
                decoration: pw.BoxDecoration(
                  color: _accentTint,
                  borderRadius: pw.BorderRadius.circular(999),
                ),
                child: pw.Text(
                  _safe('${s.key} x${s.value}'),
                  style: pw.TextStyle(
                    fontSize: 9,
                    fontWeight: pw.FontWeight.bold,
                    color: _accent,
                  ),
                ),
              ),
          ],
        ),
      ],
    ),
  );

  return doc.save();
}
